env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  quotes: ['error', 'single'],
  # we want to force semicolons
  semi: ['error', 'always'],
  # we use 2 spaces to indent our code
  indent: ['error', 2],
  # we want to avoid extraneous spaces
  no-multi-spaces: ['error'],
  react/jsx-filename-extension: [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
  #this line allows spread operator
  react/jsx-props-no-spreading: 'off',
  #this line allows import type {yourTipe}
 '@typescript-eslint/consistent-type-imports': 'error',
  #allow imports
  import/extensions: [
    "error",
    "ignorePackages",
    {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never"
    }
  ]
}
